@startuml

hide empty description

state Err

state Fetch_index {
    [*] -> Fetch_number_of_idx_ws
    state Fetch_number_of_idx_ws
    state Fetch_number_of_idx
    Fetch_number_of_idx_ws --> Fetch_number_of_idx
}

Fetch_index -left-> Err

Fetch_number_of_idx --> [*]

@enduml
